const questions = [
   "Which element appears eighth on the periodic table?",
   "What is the capital of Iceland?",
   "What year saw the founding of the Michelin tire company?",
   "What mountain is the tallest point in Ecuador?",
   "Which band released the tracks \"Monkey Wrench\" and \"Learn to Fly\"?",
   "In Norse mythology, what did Odin trade an eye for?",
   "What is an Aasvogel?",
   "Who is the only founding member of both the International Surfing and Swimming Halls of Fame?",
   "What year did the \"ILOVEYOU\" virus began infecting computers worldwide?",
   "What Grammy-­winning 1990’s band was fronted by Darius Rucker?",
   "What novel by Lucy Maud Montgomery became Canada's longest-running main stage musical?",
   "Whose sidekick was named Garth Algar?",
   "What brightly colored monkey is the world's largest?",
   "What percent of jellyfish is water?",
   "What would be scored by the Apgar score?",
   "What \"Desperate Housewives\" creator broke into TV as a personal assistant to actress Dixie Carter?",
   "What is the American equivalent of the Irish Poteen?",
   "What year was Budweiser first introduced?",
   "What was Lucy’s last name on the TV series \"I Love Lucy\"?",
   "Where are you, if you landed at Lindberg Airport?",
   "What popular computer language shares its name with the serpent Apollo slew at Delphi?",
   "In Star Wars, Obi-wan Kenobi is introduced under what pseudonym?",
   "What comedic duo of the 1920s and 1930s were real-life best friends?",
   "How much wider is a tennis court during a doubles match than a singles match?",
   "What is measured in Newtons?",
   "Which villain broke Batman's back?",
   "What folk hero does Shakespeare make reference to in his play \"The Two Gentlemen of Verona\"?",
   "Who has been played in a movie by both Denzel Washington and Mario Van Peebles?",
   "How many colors were there in the first boxes of Crayola crayons sold in 1903?",
   "What show was based on the novel \"Poor, Poor Ophelia\"?",
   "What is Indiana Jones searching for in the movie \"Indiana Jones and The Last Crusade\"?",
   "When was the first Wal-Mart store opened?",
   "Tradionally, what does a Fletcher make?",
   "Founded in 1924, what department store’s name includes the street of its original New York City address?",
   "What was the last name of husband and wife Julius and Ethel, executed for treason in 1953?",
   "What did the letters in the name of the cable network HBO originally stand for?",
   "What is the \"nogada\" in the Mexican dish \"Chiles en nogada\"?",
   "Which artist married Carrie Fisher in 1983?",
   "Who wrote Stardust?",
   "What regular character did Larry David always voice on the TV show \"Seinfeld\", even after he left the show?",
];

export default questions;
